// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umserxrsymmdtgehbcly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtc2VyeHJzeW1tZHRnZWhiY2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTYwNjQsImV4cCI6MjA1OTIzMjA2NH0.eCytxaPfQjMH9PY73dUu7ovzr-0bnYv7Mf1RJIyM2vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);