// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgyokmpiemzkfrhpusgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneW9rbXBpZW16a2ZyaHB1c2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODU3MTUsImV4cCI6MjA1OTA2MTcxNX0._GP3ny9EB2veF71T4eYEyRo2A_68REG8JG5KVG1ihhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);